# Generated by Django 4.1.7 on 2023-03-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('No_of_awards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=25)),
                ('disease_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=35)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.doctor')),
            ],
        ),
    ]
