# Generated by Django 4.1.7 on 2023-03-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medication',
            fields=[
                ('pre_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medicines', models.CharField(max_length=20)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.patient')),
            ],
        ),
    ]
